# permissions for end users to view lokis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loki-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: loki-helm-operator
    app.kubernetes.io/part-of: loki-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: loki-viewer-role
rules:
- apiGroups:
  - charts.example.com
  resources:
  - lokis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.example.com
  resources:
  - lokis/status
  verbs:
  - get
