apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: loki-helm-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Loki operator based on the helm chart with single binary mode deployment
    optionality
  displayName: Loki Helm Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - loki
  - single-binary
  - demo
  - helm
  links:
  - name: Loki Helm Operator
    url: https://loki-helm-operator.domain
  maturity: alpha
  provider:
    name: Sid
    url: skattoju.net
  version: 0.0.0
