apiVersion: charts.example.com/v1alpha1
kind: Loki
metadata:
  name: loki-sample
spec:
  loki:
    commonConfig:
      replication_factor: 1
  storage:
    type: 'filesystem'
  singleBinary:
    replicas: 1
