apiVersion: charts.example.com/v1alpha1
kind: Loki
metadata:
  name: loki-sample
spec:
  loki:
    commonConfig:
      replication_factor: 1
  storage:
    type: 'filesystem'
  singleBinary:
    replicas: 1
  # serviceAccount:
  #   create: false
  test:
    enabled: false
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    serviceMonitor:
      metricsInstance:
        enabled: false