# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/charts.example.com_lokis.yaml
- bases/monitoring.grafana.com_grafanaagents.yaml
- bases/monitoring.grafana.com_integrations.yaml
- bases/monitoring.grafana.com_logsinstances.yaml
- bases/monitoring.grafana.com_metricsinstances.yaml
- bases/monitoring.grafana.com_podlogs.yaml
#+kubebuilder:scaffold:crdkustomizeresource
